### ISSUE TITLE
NEED SUPPORT - Import Issues

### ISSUE THREAD

**Issue by manchav** [grundleborg/slack-advanced-exporter#11]
We have an issue where we import the data, however the most recent, usually within the last two days, does not import. If we import directly from Slack without the attachments we see the data, just no attachments.

We are using Mattermost 5.7

Thank you,

Manuel

**Comment by manchav** [comment]
It appears that the issue is soley around the attachments piece. We can import the emails and it works fine, but the fetch-attachments function changes things. This removes all other Public Channels except General and stops the import 3-4 days prior of the import date.

We are really in need to have this work so if someone could help it would be greatly appreciated. We are doing a migration and can't continue until this is fixed.

Thanks,
Manuel

**Comment by grundleborg** [comment]
Closing this rather old issue. If you are trying to do a Mattermost migration and having issues, please contact the Mattermost team directly for support, at https://community.mattermost.com
