### ISSUE TITLE
Need help to get the path for the attachements.

### ISSUE THREAD

**Issue by sridevikarumuri** [grundleborg/slack-advanced-exporter#2]
George, Could you help where to keep the downloaded attachments in order to be uploaded by slack. Thank you!

**Comment by grundleborg** [comment]
Please could you explain your question? I don't understand what you mean.

**Comment by sridevikarumuri** [comment]
Thank you for the quick update. With slack_advanced_exporter tool, we were able to download the attachements at path __uploads/" + post.File.Id + "/" + post.File.Name.

Could you please let me know where to keep the downloaded attachements to be used by slack import service https://<myteam.slack.com>/services/import

Thank you!

**Comment by grundleborg** [comment]
Got it. I'm afraid I don't know the answer, or if it is even possible. This tool was built to help export data our of Slack (for backups, or migration to an alternative service). I have never looked at how to import data *into* Slack.

**Comment by sridevikarumuri** [comment]
Thank you George for the update, I will investigate and let u know if I find anything. Thank you!

**Comment by grundleborg** [comment]
Closing as this issue as it's been quiet for nearly a year.
