### ISSUE TITLE
Email addresses

### ISSUE THREAD

**Issue by WGH-** [grundleborg/slack-advanced-exporter#4]
I've noticed that for some reason official workspace export .zip doesn't contain members' email addresses. However, they can be extracted using Slack API (e.g. https://gist.github.com/bahoo/59d81fc0f916d18658b1915ab615e116).

**Comment by WGH-** [comment]
I will try to implement this next week and submit it as a PR. Please ping me if I won't.

**Comment by grundleborg** [comment]
@WGH- I'd be happy to include a PR that fixes this.
